### ISSUE TITLE
Please enable RSS auto-discovery

### ISSUE THREAD

**Issue by Minoru** [spacekookie/website#1]
Hi! You've got a nice blog, keep it up! ^_^

I had to hunt for this repo, and then search within it for "rss", just to figure out the URL of your RSS feed. It would've been much easier if the site had this in its `<head>`:

```html
<link
    rel="alternate"
    type="application/rss+xml"
    href="https://spacekookie.de/rss.xml"
    title="Fun Memory Violations — Latest Posts" />
```

Then I'd simply open "Page Info" in Firefox and see the feed listed in the feeds tab.

I tried to add that line myself, so I edited crumbs/templates/components/html_head.html, but I couldn't figure out how to actually generate the HTML. `pelican content/` says it couldn't find the content, and `make html` doesn't work either. I never used Pelican before, so perhaps I simply don't know some crucial detail. Sorry I couldn't provide you with a one-click solution in the form of a PR :)

**Comment by Minoru** [comment]
Oh, of course *now* that I submitted the issue I see that `markdown` module has to be installed to build the content. PR forthcoming; sorry about the noise.

**Comment by spacekookie** [comment]
Thanks for the contribution btw :) I think I accidentally dropped the RSS link when I re-did my theme a few months ago and just never remembered to fix it :sweat_smile:
